dd_controls:
  gainsCascade: { # PID Parameters for both controllers in cascade: heading and lateral
D_heading: 0.0, 
D_lateral: 0.0, 
I_heading: 0.0, 
I_lateral: 0.0, 
P_heading: 1.0, 
P_lateral: 0.2,
horizonHeading: 1.5, # lookahead distance for the heading error
horizonLateral: 0.1  # lookahead distance for lateral error
}
  gainsPurePursuit: {
horizonSteer: 2.0,         # lookahead distance for steering value / curvature
horizonSteer_Accel: 8.0,   # lookahead distance for steering value / curvature for Accel mode
horizonSteer_SkidPad: 4.0, # lookahead distance for steering value / curvature for Accel mode
horizonVelX_1: 5.0,        # lookahead distance 1 for velocity control
horizonVelX_2: 15.0,       # lookahead distance 2 for velocity control
velocity_desired_gain: 5.0 # gain to multiply velocity function with
}
  gainsVelController: { # PID Parameters vor velocity control
D: 0.0,
D_sat: 1.0,
I: 100.0, 
P: 600.0,
enable_Integrator: 0.0,
enable_D_lowpass: 1.0
}

  settings: {
enable_debug_msgs: 1.0,

# Steering settings
steering: 0.0,                    # 0.0: Pure Pursuit 1.0: Cascade
steering_rate: 0.5,               # Max/Min steering rate possible [rad/s]
steering_rate_Accel: 0.05,         # Max/Min steering rate possible for acceleration [rad/s]

# Velocity settings
velocity_max: 20.0,               # Max allowed velocity request [m/s] (Mission übergreifend)
constant_vel_enabled: 1.0,        # 0.0: Disabled 1.0: enabled
constant_vel_desired: 2.0,        # Constant velocity in [m/s] if enabled 

acceleration_rate_limit: 1.0,     # Maximal allowed acceleration in positive direction [g] (mission übergreifend)

# Force Constraints
Fx_max: 2000.0,                    # Max allowed Fx request to vd_ecu [N]
Fx_min: -3000.0,                   # Min allowed Fx reqeust to vd_ecu [N]

Fx_Accel: 600.0,                   # Constant Fx for Acceleration mode
Fx_Inspection: 50.0,               # constant Fx for Inspection mode
Fx_recu_mission_finished: -1500.0, # Const Fx for deceleration after mission is finished 

# EBS Mode
mode_EBS: 1.0,                    # 0.0: constant Fx (Fx_EBS) used,   1.0: constant desired velocity (vel_EBS) used, 
                                  # 2.0 driving on sight with Fx_EBS, 3.0: driving on sight with vel_EBS
vel_EBS: 14.0,                    # desired velocity for EBS mode "velocity control"
Fx_EBS: 1000.0,                   # Constant Fx for EBS_Test mode

constant_Fx_enabled: 0.0,         # 0.0: Disabled, 1.0: Enabled. Overwrites Fx at the end of the model (!!)
constant_Fx_desired: 200.0,       # Fx desired in constant mode [N]

enable_localization: 0.0,         # 1.0: enables localization (driving with map depending on as_mission) 0.0: driving on sight in every mission
use_cf_finished: 0.0,             # 0.0: do not use the 'finished' signal of the conefusion as input, 1.0: use it    

accel_velocity_map: 1.0,          # 0.0: do not use predefines velocity map # 1.0 use lame velocity map # 2.0 use geht so schnell vel map # 3.0 ballern velocity map
                                  # (only useable if enable_localization is enabled) 4.0: velocity controller testing 1, 5.0 vel controller testing 2
                                  # wenn constant velocity bei accel benutzt werden soll, muss dieser parameter auch bei > 0 liegen
accel_distance: 233.0,             # distance to stop accel after [m]
enable_Spurwechsel: 0.0           # enable trajectory following with a Spurwechsel (testing purposes only - never put this to 1.0 as default value)
}

  localization: {
skidPad_start_Pos_X: 0.0,
skidPad_start_Pos_Y: 0.0

}

sdc_tracklength: 235.0            #length after which the car should stop, has to be put in manually
sdc_yawangle: -0.05             #turning angle after which the car has to stop, 1lap == 2pi

simulation: {mission: 5}


