clusterAlg: 1
ec_cluster_tolerance: 0.3
ec_max_cluster_size: 40
ec_min_cluster_size: 6
max_dist: 15
min_dist: -0.1
pass_x_higher_limit: 100.0
pass_x_lower_limit: 0.18
pass_z_higher_limit: 0.8
pass_z_lower_limit: 0.1
seg_distance_threshold_planar: 2.0
segmentation_node: {ec_cluster_tolerance: 0.2, ec_max_cluster_size: 600, ec_min_cluster_size: 20,
  seg_distance_threshold_cone: 0.9, seg_distance_threshold_planar: 333.0, use_cone_model: true}
use_sim_time: false
xmax: 10.0
xmin: -0.1
ymax: 5.0
ymin: -5.0
zmax: 500.0
zmin: -1.0
clustering_range1: 5
clustering_range2: 15
clustering_range3: 22
clustering_range4: 30
clustering_distance1: 0.4
clustering_distance2: 0.8
clustering_distance3: 1.1
clustering_distance4: 2.0
clustering_distance5: 2.5
clustering_min_sizes1: 6
clustering_min_sizes2: 2
clustering_min_sizes3: 2
clustering_min_sizes4: 2
clustering_min_sizes5: 2
clustering_max_sizes1: 1000
clustering_max_sizes2: 150
clustering_max_sizes3: 50
clustering_max_sizes4: 3
clustering_max_sizes5: 2

