stages:
  - test          # List of stages for jobs, and their order of execution
  - build

test:
    stage: test
    image: ros:foxy
    tags:
      - docker
    script:
        - colcon build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - shell
  before_script:
    - docker info
    - docker login -u $DOCKER_REPO_USER -p $DOCKER_REPO_PASS $DOCKER_REPO
  script:
    - docker build -t base-as-image .
    - docker tag base-as-image:latest $DOCKER_REPO/as/base-image:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_REPO/as/base-image:$CI_COMMIT_SHORT_SHA
    - docker tag base-as-image:latest $DOCKER_REPO/as/base-image:latest
    - docker push $DOCKER_REPO/as/base-image:latest 
